version: '3.8'
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: subject-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ../src:/var/www

  server:
    image: nginx:alpine
    container_name: subject-server
    restart: unless-stopped
    ports:
      - 9000:80
    volumes:
      - ../src:/var/www
      - ./nginx:/etc/nginx/conf.d

  database:
    image: mariadb:latest
    container_name: subject-database
    restart: unless-stopped
    ports:
      - 3309:3306
    command: ['--sql_mode=']
    environment:
      MARIADB_ROOT_PASSWORD: P@ssw0rd#db

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: subject-phpmyadmin
    restart: unless-stopped
    ports:
      - 9001:80
    environment:
      PMA_HOST: database
      UPLOAD_LIMIT: 20M
  
